# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hyperspectral_tools',
                'doc_host': 'https://reutkeller.github.io',
                'git_url': 'https://github.com/reutkeller/hyperspectral_tools',
                'lib_path': 'hyperspectral_tools'},
  'syms': {'hyperspectral_tools.core': {'hyperspectral_tools.core.foo': ('core.html#foo', 'hyperspectral_tools/core.py')}}}
