# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/constants.ipynb.

# %% auto 0
__all__ = ['s2_center_sen', 's2_fwhm_sen', 'venus_center', 'venus_fhwm']

# %% ../nbs/constants.ipynb 4
# sentinel 2
s2_center_sen=[442.7,492.4,559.8,664.6,704.1,740.5,782.8,864.7,945.1]
s2_fwhm_sen=[21,66,36,31,15,15,20,21,20]

# Venus
venus_center = [420,443,490,555,620,620,667,702,742,782,865,910]
venus_fhwm = [40,40,40,40,40,40,30,24,16,16,40,20]

